name: Update Sing-Box Alpha

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Latest Alpha Version
        id: get_version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          LATEST_TAG=$(gh api repos/SagerNet/sing-box/releases --jq '[.[] | select(.prerelease == true)][0].tag_name')
          VERSION_NUM=${LATEST_TAG#v}
          echo "version=$VERSION_NUM" >> $GITHUB_OUTPUT
          echo "tag=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: Check if Version Changed
        id: check_version
        run: |
          CURRENT_VERSION=$(grep 'version "' Formula/sing-box-alpha.rb | head -n 1 | cut -d '"' -f 2)
          if [ "${{ steps.get_version.outputs.version }}" == "$CURRENT_VERSION" ]; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Update Formula
        if: steps.check_version.outputs.changed == 'true'
        run: |
          VERSION="${{ steps.get_version.outputs.version }}"
          TAG="${{ steps.get_version.outputs.tag }}"
          URL_SOURCE="https://github.com/SagerNet/sing-box/archive/refs/tags/${TAG}.tar.gz"
          
          echo "Fetching SHA256 for Source Code..."
          SHA_SOURCE=$(curl -L -s $URL_SOURCE | sha256sum | awk '{print $1}')
          
          # 精准替换
          sed -i "s/version \".*\" # VERSION_PLACEHOLDER/version \"$VERSION\" # VERSION_PLACEHOLDER/" Formula/sing-box-alpha.rb
          sed -i "/# source_sha/s/sha256 \".*\"/sha256 \"$SHA_SOURCE\"/" Formula/sing-box-alpha.rb

      - name: Commit and Push
        if: steps.check_version.outputs.changed == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Formula/sing-box-alpha.rb
          git commit -m "Update sing-box-alpha to ${{ steps.get_version.outputs.version }}"
          git push